### ISSUE TITLE
Error when renaming wiki pages from console

### ISSUE THREAD

**Issue by ntmlod** [trac-hacks/trac-wikinotification#10]
Hello,

I have a bunch of pages that I want to "move" regarding the fake hierarchy of the wiki and it seems the best way is to proceed directly under the console with trac-admin.
I gave a try but I got an error related to the plugin unlike trough the web interface where I never had an issue.

Extract of trac.log
```
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/trac/admin/console.py", line 109, in onecmd
    rv = cmd.Cmd.onecmd(self, line) or 0
  File "/usr/lib64/python2.7/cmd.py", line 220, in onecmd
    return self.default(line)
  File "/usr/lib/python2.7/site-packages/trac/admin/console.py", line 285, in default
    return cmd_mgr.execute_command(*args)
  File "/usr/lib/python2.7/site-packages/trac/admin/api.py", line 124, in execute_command
    return f(*fargs)
  File "/usr/lib/python2.7/site-packages/trac/wiki/admin.py", line 211, in _do_rename
    page.rename(new_name)
  File "/usr/lib/python2.7/site-packages/trac/wiki/model.py", line 197, in rename
    listener.wiki_page_renamed(self, old_name)
  File "build/bdist.linux-x86_64/egg/WikiNotification/listener.py", line 71, in wiki_page_renamed
    ipnr = req.remote_addr
AttributeError: 'NoneType' object has no attribute 'remote_addr'
```

**Comment by rjollos** [comment]
@mitar: If you can grant me access to PyPI I'd be happy to upload a new version.

**Comment by mitar** [comment]
Done. :-) You are too fast for me. Thanks for helping.
