### ISSUE TITLE
Internal Server Error when notifcation email address not available

### ISSUE THREAD

**Issue by CeriMitch** [trac-hacks/trac-wikinotification#2]
An internal Server Error is produced when the email address field is not available for the session and the email address fetch returns None. Notification emails are not sent to any recipients when this occurs.

Traceback is at the bottom of the text.

I have worked around this by changing the following line in notification.py (line 170 when viewed on GitHub, 165 in my source):
```
         tos.append(cursor.fetchone()[0])
```

To:
```
         sid_email = cursor.fetchone()
         if sid_email != None:
                tos.append(sid_email[0])
```

Many thanks 
Ceri

Traceback:
```
2013-09-26 12:37:22,470 Trac[main] ERROR: Internal Server Error:
Traceback (most recent call last):
  File "/usr/lib/python2.6/dist-packages/trac/web/main.py", line 444, in _dispatch_request
    dispatcher.dispatch(req)
  File "/usr/lib/python2.6/dist-packages/trac/web/main.py", line 205, in dispatch
    resp = chosen_handler.process_request(req)
  File "/usr/lib/python2.6/dist-packages/trac/wiki/web_ui.py", line 143, in process_request
    return self._do_save(req, versioned_page)
  File "/usr/lib/python2.6/dist-packages/trac/wiki/web_ui.py", line 288, in _do_save
    req.remote_addr)
  File "/usr/lib/python2.6/dist-packages/trac/wiki/model.py", line 157, in save
    author, remote_addr)
  File "/usr/local/lib/python2.6/dist-packages/TracWikiNotification-0.2.1-py2.6.egg/WikiNotification/listener.py", line 42, in wiki_page_changed
    wne.notify("modified", page, version, time, comment, author, ipnr)
  File "/usr/local/lib/python2.6/dist-packages/TracWikiNotification-0.2.1-py2.6.egg/WikiNotification/notification.py", line 147, in notify
    NotifyEmail.notify(self, page.name, subject)
  File "/usr/lib/python2.6/dist-packages/trac/notification.py", line 241, in notify
    Notify.notify(self, resid)
  File "/usr/lib/python2.6/dist-packages/trac/notification.py", line 133, in notify
    (torcpts, ccrcpts) = self.get_recipients(resid)
  File "/usr/local/lib/python2.6/dist-packages/TracWikiNotification-0.2.1-py2.6.egg/WikiNotification/notification.py", line 165, in get_recipients
    sid_email = cursor.fetchone()[0]
TypeError: 'NoneType' object is unsubscriptable
```

**Comment by mitar** [comment]
Thanks!
