### ISSUE TITLE
KeyError: 'WikiNotification/templates'

### ISSUE THREAD

**Issue by binfalse** [trac-hacks/trac-wikinotification#6]
I just installed the plugin using 

    easy_install  TracWikiNotification

but when I enable the plugin in Trac 1.0.1 I get an error:

```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/Trac-1.0.1-py2.7.egg/trac/web/api.py", line 514, in send_error
    data, 'text/html')
  File "/usr/local/lib/python2.7/dist-packages/Trac-1.0.1-py2.7.egg/trac/web/chrome.py", line 975, in render_template
    template = self.load_template(filename, method=method)
  File "/usr/local/lib/python2.7/dist-packages/Trac-1.0.1-py2.7.egg/trac/web/chrome.py", line 933, in load_template
    self.get_all_templates_dirs(), auto_reload=self.auto_reload,
  File "/usr/local/lib/python2.7/dist-packages/Trac-1.0.1-py2.7.egg/trac/web/chrome.py", line 649, in get_all_templates_dirs
    dirs.extend(provider.get_templates_dirs() or [])
  File "build/bdist.linux-x86_64/egg/WikiNotification/web_ui.py", line 39, in get_templates_dirs
    resource_dir = resource_filename(__name__, 'templates')
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 954, in resource_filename
    self, resource_name
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 1652, in get_resource_filename
    return self._extract_resource(manager, zip_path)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 1673, in _extract_resource
    timestamp, size = self._get_date_and_size(self.zipinfo[zip_path])
KeyError: 'WikiNotification/templates'
```

Can anyone of you tell me what that means or how to fix it?

**Comment by mitar** [comment]
Try installing directly from this git repository. master branch? It seems I have not yet released the last version from the repository.

**Comment by binfalse** [comment]
Thanks, that solved the issue :)
